apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-deployment.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: ussd-service
  name: ussd-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ussd-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-deployment.yml
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: ussd-service
    spec:
      containers:
        - env:
            - name: BACKEND_URL
              value: https://bralirwalottery.rw/api
            - name: LOG_LEVEL
              value: debug
            - name: WEB_URL
              value: https://bralirwalottery.rw
            - name: POSTGRES_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres.postgres.credentials.postgresql.acid.zalan.do  # Name of your secret
                  key: password  # Key of your secret
          image: qonicsinc/lottery-ussd-service:1.0.22
          name: ussd-service
          ports:
            - containerPort: 9000
              protocol: TCP
      restartPolicy: Always
      imagePullSecrets:
        - name: qonicsinc-dockerhub
